# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ceEdges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directed', models.CharField(default='', max_length=200)),
                ('props', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='ceNodes',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('props', models.TextField(default='{}')),
            ],
        ),
        migrations.AddField(
            model_name='ceedges',
            name='n1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n1', to='CodeExplorer.ceNodes'),
        ),
        migrations.AddField(
            model_name='ceedges',
            name='n2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n2', to='CodeExplorer.ceNodes'),
        ),
    ]
